In [1]:
import numpy as np
import pandas as pd
from keras.models import Sequential
from keras.layers import Dense
from keras import optimizers
from keras.layers import Dropout
import keras
from sklearn import preprocessing
from sklearn.model_selection import train_test_split

data = pd.read_csv('dataset/weather.csv')

data = data.apply(preprocessing.LabelEncoder().fit_transform)

data = data.values    

X, y = data[:, 1:], data[:, 0]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.1, random_state=42)

layer = 4
nodes = [4, 3 , 2, 3 ,1]
epoch = 10
batch = 2

print('X_train')
print(X_train)

print('X_test')
print(X_test)

print('y_train')
print(y_train)

print('y_test')
print(y_test)

Using TensorFlow backend.


X_train
[[1 0 0 0]
 [1 1 0 1]
 [0 1 1 0]
 [0 1 0 1]
 [1 0 0 1]
 [1 0 1 0]
 [2 0 1 0]
 [0 1 0 1]
 [2 0 0 0]
 [2 1 1 1]
 [2 0 0 1]
 [0 1 1 1]]
X_test
[[2 1 0 1]
 [2 0 1 1]]
y_train
[2 0 1 2 0 2 1 1 2 2 1 0]
y_test
[1 0]


In [2]:

model = Sequential()

for i in range(0,len(nodes)):
    if i == 0:
        model.add(Dense(units=nodes[1], activation='sigmoid', input_dim=nodes[0]))
        model.add(Dropout(0.1))
    elif i == len(nodes)-1:
        model.add(Dense(units=1, activation='sigmoid'))
    else:
        model.add(Dense(units=nodes[i+1], activation='sigmoid'))
        model.add(Dropout(0.1))

In [3]:
sgd = optimizers.SGD(lr=0.01, decay=1e-6, momentum=0.9, nesterov=True)

model.compile(optimizer=sgd,
              loss='binary_crossentropy',
              metrics=['accuracy'])

In [4]:
model.fit(X_train, y_train, batch_size=batch, nb_epoch=epoch, verbose=1)

/usr/local/lib/python3.5/dist-packages/ipykernel_launcher.py:1: UserWarning: The `nb_epoch` argument in `fit` has been renamed `epochs`.
  """Entry point for launching an IPython kernel.


Epoch 1/10
12/12 [==============================] - 1s 53ms/step - loss: 0.8748 - acc: 0.2500
Epoch 2/10
12/12 [==============================] - 0s 2ms/step - loss: 0.6225 - acc: 0.5000
Epoch 3/10
12/12 [==============================] - 0s 2ms/step - loss: 0.3906 - acc: 0.3333
Epoch 4/10
12/12 [==============================] - 0s 2ms/step - loss: 0.1713 - acc: 0.3333 
Epoch 5/10
12/12 [==============================] - 0s 2ms/step - loss: 0.0332 - acc: 0.3333
Epoch 6/10
12/12 [==============================] - 0s 2ms/step - loss: -0.1095 - acc: 0.3333
Epoch 7/10
12/12 [==============================] - 0s 2ms/step - loss: -0.1244 - acc: 0.3333
Epoch 8/10
12/12 [==============================] - 0s 2ms/step - loss: -0.2666 - acc: 0.3333
Epoch 9/10
12/12 [==============================] - 0s 2ms/step - loss: -0.2966 - acc: 0.3333
Epoch 10/10
12/12 [==============================] - 0s 2ms/step - loss: -0.4067 - acc: 0.3333


In [5]:
score = model.evaluate(X_test, y_test, verbose=0)
print(score)

[1.493064045906067, 0.5]
